### ISSUE TITLE
Search bar for article given at customer panel not response

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/community-skeleton#22]
### To find article by login to customer panel, unable to find given article below : 

![screenshot 1](https://user-images.githubusercontent.com/43210406/49569087-f3f29600-f958-11e8-9dfc-1e9d8e033390.png)

**Comment by papnoisanjeev** [comment]
fixed

**Comment by shubhwebkul** [comment]
resolved

**Comment by vaishaliwebkul** [comment]
Still unable to search article from the customer's profile page.
