### ISSUE TITLE
Close ticket from reply and maybe customize ticket status?

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/community-skeleton#354]
I asked if is possible to lock a ticket from customer replies but no answer for now
https://forums.uvdesk.com/topic/1903/lock-a-ticket-from-response

Asked also on Skype but still a mystery

- I don't understand what is difference between closed and resolved status. Just a different label but the same thing?
- Sometime can be useful to be able to have a status ticket that lock the ticket from new answer sent by the web interface or by email. Is this already possible?
- Will be useful can manage ticket status by adding maybe more status or customize the status. Not necessary but nice. I'm thinking and asking, if the possibility to lock a ticket will be inserted will need a new ticket status like closed and locked and maybe a banner that inform the operator user will be unable to reply to the ticket.

**Comment by Himaniwebkul** [comment]
@PeopleInside 
**I don't understand what is difference between closed and resolved status. Just a different label but the same thing?**
>> We can differentiate both statuses in the following manner:
**Resolved**: When agents are reasonably sure that they have provided the customer with a solution to their problem, they can change the status of the ticket to Resolved.
**Closed**: When customers confirm that their problem has been resolved then you can mark the ticket as closed. Indeed, the resolved ticket can be turned into the closed.

**Sometimes can be useful to be able to have a status ticket that locks the ticket from a new answer sent by the web interface or by email. Is this already possible?**
>> Currently, with the default community helpdesk, there is no luck to get this feature but can be done by customizing the code script.

Thank You!!

**Comment by vaishaliwebkul** [comment]
@PeopleInside 
any update on the same as mentioned by @Himaniwebkul ?? or this issue should be closed?

**Comment by PeopleInside** [comment]
@vaishaliwebkul can this issue still be opened requesting as feature to allow locking of a ticket?

Will be nice to have a status closed and locked where customer cannot reply to the ticket.
If not means user will be still able to open and re open a ticket again or simply need to be ignorated. Operator need to cancel, delete a ticket because the ticket cannot be locked.

**Comment by PeopleInside** [comment]
I see now there is close discussion in a ticket clicking near the operator message.
Maybe this issue can be closed if there is an option to lock the ticket from be updated by the customer.
Closing for now.

**Comment by PeopleInside** [comment]
Cannot find anymore how to lock a ticket. Reopening

**Comment by PeopleInside** [comment]
When you are on a ticket and made a reply to the customer, after sending it and see the reply in the ticket UI you can move the mouse pointer near the operator name and avatar on the reply where there is a three fullstop menu as showed below:

![0](https://user-images.githubusercontent.com/5006150/209675220-8c988dc3-0fe0-42e4-bba1-b24e19c1187f.png)

When pressed a menu allow to use a lock thread button.
After pressed this you will see a locked message:

![1](https://user-images.githubusercontent.com/5006150/209675398-3d5d2f53-2d69-4cc5-88f5-1ac503834377.png)

So I was thinking this locks the possibility to have ticket replied again and reopen even from the customer but is not customer will see nothing and will still be able to post a reply and reopen the ticket.

Why?
Why this lock function exist but do not nothing?
It works only for a different operator and not for the customer?

Still be useful add an option to lock the thread for the customer.

**Comment by PeopleInside** [comment]
Also the relative guide in UVdesk, on my opinion, never explain well what lock thread means.
https://support.uvdesk.com/en/blog/editing-deleting-and-locking-the-threads

There is also a BUG on this article because if I try to vote as not useful an error message say that article never exist.

![immagine](https://user-images.githubusercontent.com/5006150/209680988-3e35b183-0930-46bd-ae50-3623c1898646.png)

Again I hope you can allow lock thread for lock replies from customer.
Actually the lock thread doest do this, is not clear what this option do also from the guide linked.
