### ISSUE TITLE
An error occurred when the agent was deleted

### ISSUE THREAD

**Issue by yjqphp** [uvdesk/community-skeleton#659]
# Bug report

###  issue
       1.  An error occurred when the agent was deleted;
       2. The agent whose role is adminstrator cannot be deleted

### Steps to reproduce

    1. Create a customer，eg： abc@gamail.com

    2. Create a same mailbox agent,    eg: abc@gamail.com

    3.  deleted agent

### Expected result

*   The system is deleted successfully, and the db has no record

### Actual result

1.  Doctrine throw exception with getOneOrNullResult
2. A message is displayed indicating that the agent is deleted successfully, but the agent is not deleted

**Comment by papnoisanjeev** [comment]
@yjqphp 

We have already fixed this issue and [pull request ](https://github.com/uvdesk/core-framework/pull/632/files) is already created for the same and will reflect in next release of project.

Till then you can fix the same on your project  by updating  file **vendor/uvdesk/core-framework/Controller/AccountXHR.php** on [line](https://github.com/uvdesk/core-framework/blob/c8529f47b50cebdce1794a4d4bb9f7b3ad7e40bf/Controller/AccountXHR.php#L72) no 72.

**Comment by yjqphp** [comment]
That's great! The role of the proxy user is Administrator. The system displays a message indicating that the db server is deleted successfully, but the DB server is not deleted. The problem is still there.

**Comment by Komal-sharma-2712** [comment]
Now this issue has been resolved now in uvdesk latest release v-1.1.3 version, so we are closing this issue.
